### ISSUE TITLE
Positive Result by Hybrid Analysis

### ISSUE THREAD

**Issue by antuketot76** [SimpleMobileTools/Simple-Draw#101]
Hey, below are the apk test result from Hybrid Analysis.
Hybrid Analysis Link : [HERE](https://www.hybrid-analysis.com/sample/59bb3978586cd0fa313f15510b58ae98788cad2e211e7e400d7481ddb2076ed2/5ae7c6627ca3e141b56fa738)
![image](https://user-images.githubusercontent.com/33280865/39458110-36aac82e-4d2d-11e8-9aba-ca1256b30084.png)

**Comment by tibbi** [comment]
well that was expected, thanks :)
