### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [SimpleMobileTools/Simple-Draw#105]
Hi @tibbi 

I found [this app called Drawing Easy Draw On Screen](https://play.google.com/store/apps/details?id=com.wildstudiomotion.drawdraw) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by Poussinou** [comment]
I already know you don't care about [that](https://github.com/SimpleMobileTools/Simple-Gallery/issues/855), but pinging you is a good thing in my opinion (to let you know where they are), and it allows me to track this fake developers more easily :)

**Comment by tibbi** [comment]
thanks

**Comment by bb1a2** [comment]
Check this one out too:

https://play.google.com/store/apps/details?id=com.draw.me

**Comment by bb1a2** [comment]
You can contact google. Don't they violate the Apache license?

Google are not the fastest to respond but they usually do under pressure (and bad publicity).

**Comment by tibbi** [comment]
maybe they do, but there are so many clones out there that reporting them would take me a lot of time. Just giving many bad ratings seems to do it.

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=com.beta.draw
