### ISSUE TITLE
predefined set of standard colors 

### ISSUE THREAD

**Issue by HoWilgh** [SimpleMobileTools/Simple-Draw#107]
Please add a set of ~20 standard colors which can easily (fast) be selected.
The current color selection mode makes it difficult to often select some standard without remembering an entering the Hex colors. I suggest to use the current color selection as an advanced Option.

**Comment by ppp0099** [comment]
I suggest a color picker history with

1. pinned colors feature and
2. swipe-to-remove-from-history.

**Comment by tibbi** [comment]
some default colors will be added in 6.5.0, I dont plan adding a classic colors bar now
