### ISSUE TITLE
Draw listed as an app to take photos

### ISSUE THREAD

**Issue by Maxime-J** [SimpleMobileTools/Simple-Draw#112]
Following the discussion in #47,
it might be better to remove the support of the IMAGE_CAPTURE intent.
This intent is designed for apps wanted to capture an image with a camera app.

It's confusing for a user to see Draw listed when he expects to take a photo.
When using [Notebloc](https://play.google.com/store/apps/details?id=com.notebloc.app) for example.

What's your take on that?

**Comment by tibbi** [comment]
it was added intentionally indeed, and I want to keep it
