### ISSUE TITLE
Error when building 6.0.0

### ISSUE THREAD

**Issue by licaon-kter** [SimpleMobileTools/Simple-Draw#122]
Log: https://gist.github.com/licaon-kter/4cf96b89a2d061c3a51ba672d446ed2e

What am I missing exactly?

**Comment by tibbi** [comment]
not sure, try pressing Refactor -> Migrate to AndroidX

**Comment by licaon-kter** [comment]
`gradle` has no refactor

**Comment by tibbi** [comment]
I mean in android studio

**Comment by licaon-kter** [comment]
So this can't be build with `gradle` like Notes and Gallery and FileManager and Contacts now?

**Comment by tibbi** [comment]
it should be possible. But I dont have experience building without android studio.

**Comment by licaon-kter** [comment]
Fixed in: https://github.com/SimpleMobileTools/Simple-Draw/commit/01744b50680b42f02017d6160dbce0cdccbbe6d8
