### ISSUE TITLE
Simple-Draw Pro / F-Droid

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Draw#125]
Hi Tibor,

just a question: all other pro versions, e.g. Simple Contacts, Calender, ...., have arrived in F-Droid, for a while now. Even some upgrades, afterwards.

Simple Draw is still on 4.3.1 in -F-Droid, any ideas why?

Not an issue to wait, but I'm curious.

Kind regards,
Michael

**Comment by tibbi** [comment]
they are having some issues with compiling it, I will take a look at it soon
