### ISSUE TITLE
Implement opening existing images

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Draw#13]

**Comment by XyLoNaMiyX** [comment]
I was just thinking, would this load an already-made image (like `.png`) or would you add the possibility to save in a custom format which kept all the information (i.e. paths drawn)?

In the later case I thought of a dropdown box (a `spinner` like Android calls them) which allowed to select the format (would also open the possibility to `.svg`) – but some of my design decissions are horrible so maybe it's not a good idea ;)

**Comment by XyLoNaMiyX** [comment]
Custom format would even open the possibility to undo paths on already made drawings. Maybe something like:
```xml
<drawing>
  <path>
    <point/line … />
  </path>
  <path>
    …
  </path>
</drawing>
```

And so one would be able to undo the later `<path>`'s.

**Comment by tibbi** [comment]
ah thats just too advanced, starting with saving a simple .png or .jpg will be good enough. Draw is not really an app with high priority for now, so even that will have to wait some more time.

**Comment by HoWilgh** [comment]
+1 for reopening saved images (.svg)
