### ISSUE TITLE
Add handling for Edit intent

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Draw#131]

**Comment by theotheroracle** [comment]
this is not working properly for me on lineage 18.1
its just blank when openinh an edit intent but share intent works fine

**Comment by tibbi** [comment]
what is blank? Are you opening a casual .jpg image? What app version are you using?

**Comment by theotheroracle** [comment]
blank canvas
same image works when opening via a share intent
just a .jpeg
version 6.6.0 pro (from fdroid)

**Comment by tibbi** [comment]
will keep an eye on it
