### ISSUE TITLE
zooming creates dots 

### ISSUE THREAD

**Issue by HoWilgh** [SimpleMobileTools/Simple-Draw#136]
If you zoom, small dots or lines are drawn at the position of the fingers before zooming starts. 
It would be good to suppress the last line when zooming is detected.

**Comment by tibbi** [comment]
if you start the zooming gesture with both fingers together, nothing will be drawn. It can always be improved, of course.

**Comment by HoWilgh** [comment]
This would mean you only can zoom in but not zoom out.

**Comment by HoWilgh** [comment]
> if you start the zooming gesture with both fingers together, nothing will be drawn. It can always be improved, of course.

I tested this and it does not work for me

**Comment by MaDDmin** [comment]
I was about to write the zoom feature request, and found it was already  there. It doesn't work at all for me :( 
I'm using a Mi Max 3.

**Comment by tibbi** [comment]
shouldnt be happening anymore
