### ISSUE TITLE
linewidth should be relative to size of the canvas 

### ISSUE THREAD

**Issue by HoWilgh** [SimpleMobileTools/Simple-Draw#137]
Lines are shown differently If drawn at different zoom levels. 
Therefore, the linewidth should be relative to size of the canvas and should not be dependent on the zoom level.

**Comment by HoWilgh** [comment]
I did attach an image showing several lines drawn with the same thickness but at different zoom levels....

![image](https://user-images.githubusercontent.com/9978035/55182690-84661800-518e-11e9-858c-9a2608a3aba0.png)

**Comment by tibbi** [comment]
I want to keep it this way
