### ISSUE TITLE
The color of CustomizationActivity changes after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Draw#149]
When I change the orientation of the device screen, the color of the activity CustomizationActivity changes
![2019-07-18 15-13-49_before](https://user-images.githubusercontent.com/53469180/62210779-40358f00-b39d-11e9-9e78-c255a6814973.png)
![2019-07-18 15-13-49_after](https://user-images.githubusercontent.com/53469180/62210780-40358f00-b39d-11e9-9832-3d01b5d7a3ef.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
