### ISSUE TITLE
LicenseActivity doesn't keep the scroll position after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Draw#150]
When I change the orientation of the device screen, LicenseActivity doesn't keep the scroll position
![2019-07-18 04-14-35_before](https://user-images.githubusercontent.com/53469180/62211015-cc47b680-b39d-11e9-9764-d70404192768.png)
![2019-07-18 04-14-35_after](https://user-images.githubusercontent.com/53469180/62211016-cc47b680-b39d-11e9-9c1c-b1f19bc3348c.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
