### ISSUE TITLE
MainActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Draw#151]
When I change the orientation of the device screen, MainActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
A TextView appears
![2019-07-18 05-40-13_before](https://user-images.githubusercontent.com/53469180/62211151-1b8de700-b39e-11e9-8012-f748b672171d.png)
![2019-07-18 05-40-13_after](https://user-images.githubusercontent.com/53469180/62211152-1b8de700-b39e-11e9-82dd-852f616be437.png)

-- second case --
The files lose their image icons 
![2019-07-18 03-46-59_before](https://user-images.githubusercontent.com/53469180/62211153-1b8de700-b39e-11e9-8ff6-b528a76a3ac0.png)
![2019-07-18 03-46-59_after](https://user-images.githubusercontent.com/53469180/62211154-1c267d80-b39e-11e9-89c2-5e1c2a48bfd5.png)

-- third case --
The Dialog disappears
![2019-07-18 03-42-33_before](https://user-images.githubusercontent.com/53469180/62211155-1c267d80-b39e-11e9-8f42-24e1265da74d.png)
![2019-07-18 03-41-46_after](https://user-images.githubusercontent.com/53469180/62211156-1c267d80-b39e-11e9-8421-c4ae1b2a7edb.png)

-- fourth case --
One of the arrows disappears
![2019-07-18 03-21-33_before](https://user-images.githubusercontent.com/53469180/62211157-1c267d80-b39e-11e9-9b0c-b911ea6f732c.png)
![2019-07-18 03-21-33_after](https://user-images.githubusercontent.com/53469180/62211158-1c267d80-b39e-11e9-8344-cfdcddc28256.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
