### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by kenneth-Q** [SimpleMobileTools/Simple-Draw#153]
Thank you for the useful software. I often use it at school ( take note, mathematical operations, etc). But I think it could be better.
Those are idea for proposal:

![20190906_182311](https://user-images.githubusercontent.com/11911577/64423969-6952e900-d0da-11e9-9755-182da195e8d8.png)
1. Click to enter the full screen ( hide system_statue_bar and hide app_top_bar  )
2. Click to zoom in/out
3. Click to lock/unlock the draw layout
4. Click to move the view to up/down/left/right
5. Click to hide/display the tools ( move_view, lock_layout, zoom, )
6. Click to choose the color

Sorry for my pooooooor English.
Thanks.

**Comment by tibbi** [comment]
that is way beyong the scope of the app, and the system decides how many buttons are visible at the top bar. Also, report just 1 thing per issue please.
