### ISSUE TITLE
'Storage' permission not present, unable to save files

### ISSUE THREAD

**Issue by mtris** [SimpleMobileTools/Simple-Draw#190]
Dear Simple Mobile Tools Team: I just got a new phone (LG with OS 10). After installing Draw, I was unable to save files, or choose file path. I noticed in the App info page that the permissions section is greyed out as "No permissions requested". There is no slide to allow storage (or any permissions).
Is It possible that a pre-installed app is needed for the function?  I disable as much as I can (for sec/priv), but wondered if it's possible I my have to enable something, for Draw to function.
I appreciate the entire suite of Simple Mobile Tools apps, and thank you for your time. Sincerely,

**Comment by tibbi** [comment]
You dont need the storage permission on Android 10, it uses the new storage access framework forced by Google. Just use the Save button at the top menu and name your file.
