### ISSUE TITLE
Changing the thickness

### ISSUE THREAD

**Issue by HoWilgh** [SimpleMobileTools/Simple-Draw#20]
Changing the thickness would dramatically enhance the types of use.

**Comment by XyLoNaMiyX** [comment]
Hasn't this one been resolved already?

**Comment by tibbi** [comment]
ye it was, thanks

**Comment by HoWilgh** [comment]
it is a little bit hidden in the settings.
Thx.

**Comment by tibbi** [comment]
ye its hidden intentionally, as very most people wont need it. I want to keep the base UI as simple as possible at all apps

**Comment by XyLoNaMiyX** [comment]
> as very most people wont need it

However, isn't default thickness _way_ too thin now? I mean, before this setting, I would swear the thickness was larger to start with.

**Comment by tibbi** [comment]
as I see theres a bug now. If you clear your app data and start the app for the first time, the thickness is ok. If you restart it, its way too thin. Ill take a look at it later.
