### ISSUE TITLE
App is outdated on F-Droid compared to Google Play

### ISSUE THREAD

**Issue by Starcr0ss** [SimpleMobileTools/Simple-Draw#260]
I prefer to get my apps from F-Droid whenever possible, and I still cannot make the jump to F-Droid for this app. As of right now the app is at v6.8.2 on F-Droid while it is at v6.9.0 on Google Play. Is there any way that the app can be kept closer to up-to-date on F-Droid?

**Comment by tibbi** [comment]
F-droid is usually a couple days behind, nothing we can do about it. 6.9.0 has been released just yesterday...
