### ISSUE TITLE
Pan.

### ISSUE THREAD

**Issue by Noitarud** [SimpleMobileTools/Simple-Draw#275]
When someone begins they generally start in the middle, but then realise they need to add a detail on the side that requires the image to be shifted…

At this time the only way to shift is to rotate the device and you get a larger canvas which gets cut off when you save. (See next issue)

**Comment by tibbi** [comment]
you can already move the canvas by fingers aswell

**Comment by Noitarud** [comment]
But I would like to add, that I wanted to do pan only so my brush strokes stay the same size (that was why I ruled pinching out completely)- how about scaling the brush diameter when zooming? Maybe the line the knob slides could move if there are software limits to brush size…

cannot reopen ;)
