### ISSUE TITLE
Should 'Undo' undo open file?

### ISSUE THREAD

**Issue by Noitarud** [SimpleMobileTools/Simple-Draw#279]
I begin another image and think "I'll use the colours from the other"(nonliterally) so I open the image and dab the colour and press undo to go to the previous image, but I discover when I pressed open file it placed it behind what I had already drawn and the undo removed the last stroke! seems to mean I need to save a blank canvas to clear it. (Much later noticed option Change background colour, no effect.)

**Comment by tibbi** [comment]
sure, whatever you do, it undoes

**Comment by Noitarud** [comment]
But it didn't. If I want to clear I have to make load a blank…
