### ISSUE TITLE
Clarify compression artifacts on saved images that user reloads

### ISSUE THREAD

**Issue by Noitarud** [SimpleMobileTools/Simple-Draw#280]
Ultimately a filter.
The image will look neater zoomed in if the distortions from artifacts are cleaned up by ascertaining average colour of region, but its your time.

My computer has PNG saveing and that does not add artifacts - is the PNG here supposed to be a lossy one (or is there a JPEG middle step?) to create them?

**Comment by tibbi** [comment]
png shouldnt create artefacts, jpg should

**Comment by Noitarud** [comment]
Mine has.
![Screenshot_20230502-212305](https://user-images.githubusercontent.com/98794719/235653697-36f8e805-2c13-4cbc-9202-1b204bf7a39a.png)

**Comment by Noitarud** [comment]
Maybe its okay in this version? I will see if it keeps going
