### ISSUE TITLE
Support for themed icons

### ISSUE THREAD

**Issue by AvidGithubUser** [SimpleMobileTools/Simple-Draw#284]
Some of the other Simple Mobile apps support the feature, hoping it will be added to this one as well.

**Comment by tibbi** [comment]
what do you mean? All apps handle icons the same

**Comment by AvidGithubUser** [comment]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by tibbi** [comment]
we support that already

**Comment by AvidGithubUser** [comment]
That is strange. Then why does the icon color not change when added to the home screen? Other apps like Calendar and Voice Recorder change according to the theme, but the icon for this app remains the same, static color.

**Comment by tibbi** [comment]
what app and OS version you use at all?

**Comment by AvidGithubUser** [comment]
6.9.2 Pro, Android 13.
