### ISSUE TITLE
Add Zoom

### ISSUE THREAD

**Issue by fabio963** [SimpleMobileTools/Simple-Draw#29]
Could work like the zoom of the F-droid app Markers, but needs to support bigger images and have a (temporary) ruler to better judge the zoom.

**Comment by XyLoNaMiyX** [comment]
I wonder if you could use the volume buttons to change the zoom? It would be the less intrusive way in my opinion. Or maybe a `CheckBox` "Use volume buttons to zoom" on the settings.

**Comment by HoWilgh** [comment]
This feature is really needed urgently. Drawing detailed notes is not possible without it. 
Thanks in advance.

**Comment by tibbi** [comment]
optional zoom will be added in 4.3.0. The focal point will always be the center of the screen for now, I couldnt make it work as I wanted even after spending quite a few days on it..

**Comment by ppp0099** [comment]
Thanks for implementing it.

A couple of noncritical bugs, however (mutually related, I think):

1. sometimes (couldn't pinpoint exactly when), the first tap of a zoom gesture leaves a brush stroke;
2. zoom motions register as history events.

**Comment by HoWilgh** [comment]
Hi, 
Thanks for working on this feature. 

I also saw the behaviour ppp0099 mentioned. 
Additionally, if you zoom out and see of the drawing as much as possible it is not possible to draw longer lines!

**Comment by linsui** [comment]
Great feature, thanks. It will be better if I can move the canvas with gestures.

**Comment by Lonami** [comment]
Not sure what the state of this issue is, but I had an idea to make it simple and convenient to use. The first tap indicates the **center** of the zoom. If there is not a second tap, it can freely draw. If a second tap occurs while the first is holding, anything the first tap drew is erased, and moving the second finger (up/down or against the first tap?) zooms in and out.

**Comment by tibbi** [comment]
that isnt really convenient or intuitive at all, I havent seen such behaviour anywhere yet. Zooming with gestures is the native way of doing it.

**Comment by Lonami** [comment]
Just from the development view of point, I'd say it's easier than detecting a gesture and then averaging and whatnot. Quite sure people would get used to it soon, but eh, just my two cents.

**Comment by tibbi** [comment]
it doesnt matter what is easy to implement, I want to use gestures commonly used and known by people, not invent something new

**Comment by tibbi** [comment]
zooming with moving will be added in 6.3.0
