### ISSUE TITLE
Simple Draw Pro the latest version doesn't start 

### ISSUE THREAD

**Issue by aswedaw** [SimpleMobileTools/Simple-Draw#291]
It doesn't start or work on Android 10 MIUI
China ROM devices.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by tibbi** [comment]
it doesnt work even after reinstall?

**Comment by aswedaw** [comment]
App version 6.9.4(Build number 80)

**Comment by tibbi** [comment]
does it work when installed from https://github.com/SimpleMobileTools/Simple-Draw/releases ? Find the .apk file.

**Comment by mario-g98** [comment]
> does it work when installed from https://github.com/SimpleMobileTools/Simple-Draw/releases ? Find the .apk file.

No, it also doesn't start from the GitHub apk on Android 13

**Comment by tibbi** [comment]
how about this one? Sending build from hash d09b75d4b2 (note to myself). Remove ".zip" extension by simple renaming, do not try decompressing the file. Github doesnt allow sending .apk files directly.

[draw-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Draw/files/12556999/draw-core-release.apk.zip)

**Comment by mario-g98** [comment]
This one works, but it says it is 6.9.3. The problem is with the newest one

**Comment by esensar** [comment]
@mario-g98 can you try this APK? It is built from #292 
It is signed with a different key, so you may need to manually uninstall the app before installing this version
[draw-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Draw/files/12559208/draw-core-release.apk.zip)

**Comment by aswedaw** [comment]
I can't install this apk.

**Comment by aswedaw** [comment]
Thanks to LORD,it works!

**Comment by aswedaw** [comment]
Thanks to LORD,it works!👍
