### ISSUE TITLE
Name: "Draw" or "Simple Draw"?

### ISSUE THREAD

**Issue by 6arms1leg** [SimpleMobileTools/Simple-Draw#31]
First of all, thanks for this great app!
I was searching for a [JetDraw](https://play.google.com/store/apps/details?id=com.styluslabs.paint) FOSS replacement for a long time and now I finally found this nice app. Although its still missing some features, its already one of my favorite apps – not bloated, following the KISS principle...
However, I'm quite confused by the app name: F-Droid lists it as "Draw", here it's name is "Simple Draw". Is there a reason for this non-consistent app name? Otherwise I would suggest to stick to one name, so it can be found on all platforms (e.g. F-Droid and GitHub) easily.
Merry Christmas! :santa:

**Comment by tibbi** [comment]
Hello, well having "Simple" in the name helps if somebody searches for it, its a pretty important word. Its used on both playstore and github, F-droid is using the actual apps launcher name, Ill check if I can change it there.

**Comment by XyLoNaMiyX** [comment]
> Hello, well having "Simple" in the name helps if somebody searches for it, its a pretty important word.

I completely agree with that, it's a bit harder to find the application because many others also use "simple" in their description.

> F-droid is using the actual apps launcher name

Maybe if all the apps had "Simple " prefixed that would also help make them appear together on alphabetically-sorted launchers?

**Comment by tibbi** [comment]
they used to have the "simple" prefix even if downloaded from playstore in the beginning, but it was awkward to see them grouped together with the typical orange icons. Also if somebody is looking for a Camera, he should not have to go to S.

**Comment by 6arms1leg** [comment]
> they used to have the "simple" prefix even if downloaded from playstore in the beginning, but it was awkward to see them grouped together with the typical orange icons. Also if somebody is looking for a Camera, he should not have to go to S.

Actually, I disagree.
If I install an app called "simple draw" I would expect to find it in the *S* menu group. I had a hard time finding it on my mobile. Same goes for "simple camera". It may not be very convenient but at least it is consistent and the (logically) expected behavior.
And I think the problems caused by non-consistent naming are far more important: Searching for "simple draw" on F-Droid does not return your app as a search result.
Also, I think it just confuses users (at least I was): Installing an app called "simple draw" which is named "draw" after installation.

I would recommend to rename it again with the "simple" prefix.
Or even better: choose a more distinguishable name all together. Both key words of each app are so generic, they return either lots of matching search results (Google play store) or none due to the non-consistent naming scheme (F-Droid). E.g., there are lots of apps on the Google play store called "simple camera" while there are none on F-Droid.

**Comment by XyLoNaMiyX** [comment]
> Actually, I disagree. […]

You've got a point on your reasoning!

> Or even better: choose a more distinguishable name all together.

This is a bit harder. The team is "**Simple** Mobile Tools" and their apps are **Simple** apps. I think that should not be changed, for the searches not to return so many results, something more unique should be used — but sadly, this probably means there's no direct relation between the chosen name and what the application would do (unless it was some kind of pre/suffix, but again, people would need to learn it).

Also I think they don't really have a problem with not being visible. Their applications have thousands of downloads on the Play Store (> 50,000 both Gallery and Calendar) already and a very good rating on average.

**Comment by 6arms1leg** [comment]
@XyLoNaMiyX, yes, renaming might go a little too far – I see that. I just wanted to mention that while I totally enjoy the Simple Draw app, its name is somewhat troublesome/unfortunate concerning search results and recognition.
So I strongly suggest to just pick one name and stick to it: "Simple-Draw", "Simple Draw", "SimpleDraw", etc..., it doesn't matter as long as it's the same everywhere.

Anyway, I didn't mean to criticize – It's a great app and I just want it to become even better. Thanks for your work!

**Comment by tibbi** [comment]
I want to focus on the big picture and features instead of getting lost in such details. It apparently doesnt matter how are the apps called, there will always be a lot of people wanting the other name... Ill leave playstore as it is, maybe Ill add the "simple" prefix to fdroid someday as the search there is quite primitive.

**Comment by 6arms1leg** [comment]
:disappointed: Never mind.
