### ISSUE TITLE
Rotation option

### ISSUE THREAD

**Issue by AlfaOmega33** [SimpleMobileTools/Simple-Draw#32]
Please, add an ability to rotate the image;

Or, in alternative, change the position of the color box (for example on the bar)

**Comment by XyLoNaMiyX** [comment]
I just implemented this but the drawing doesn't rotate itself, but rather you can rotate the screen. Let me show you:

![eh](https://cloud.githubusercontent.com/assets/6297805/21770018/c2f9f8aa-d681-11e6-920b-602e401bf51e.gif)

(Sorry for the huge `.gif`) — I made use of [this](http://stackoverflow.com/a/14290835) to save maps into a parcelable, [this](http://stackoverflow.com/a/3542895) to save the state of the canvas and [this](http://stackoverflow.com/a/8127953) (comment) to make the `Path` serializable. Should I make a PR yet, or am I missing something?

**Comment by tibbi** [comment]
well if theres not too many changes, you can try creating some PR. Dont care about the disappearing dialog, I usually dont care about rotations at all. It just doesnt happen that often to waste too much time on it.

**Comment by XyLoNaMiyX** [comment]
> well if theres not too many changes, you can try creating some PR

Okay awesome!

> I usually dont care about rotations at all

Neither did I until some of my users found out that some rotation changes involved data loss… I always use the phone in portrait, but the rotation change may happen accidentally! I'll remove that part from the code though.
