### ISSUE TITLE
Add rubber

### ISSUE THREAD

**Issue by Jiack214** [SimpleMobileTools/Simple-Draw#40]
Could you add a rubber mode to quickly erase?
This should be a simple button that sets pen color as background and increases a bit the thickness.

**Comment by ppp0099** [comment]
Please consider removing the minimum size of the eraser. I didn't even realize that that restriction was supposed to represent the wider end of a virtual pencil, whereas it is sometimes limiting when you want to use the eraser to draw a fine line with the background color on a non-background color.
