### ISSUE TITLE
Invocation intent

### ISSUE THREAD

**Issue by daniele-athome** [SimpleMobileTools/Simple-Draw#47]
I'd like to integrate [Kontalk](https://github.com/kontalk/androidclient) with your app, in such a way that I can send an intent to invoke your app, the user draws something and, when finished, the output is returned to Kontalk so it can be sent as a message. What do you think? The intent can be used by other apps as well of course.

You could use (along with your custom intent name) the [IMAGE_CAPTURE intent](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE) so the interface would be standard.

**Comment by tibbi** [comment]
hey, sounds good. The Draw does not currently have a high priority tho, so it might take some time to get to it.

**Comment by tibbi** [comment]
Ive cheked a couple popular drawing apps, none of them reacted to image_capture. I still implemented it tho, it can have some nice uses. Seems to be working with Kontalk as long as the media.extra_output is a file:// uri. Thanks

**Comment by daniele-athome** [comment]
Great, thanks!! 
By the way if you think that another intent would be more suited, please suggest it.

**Comment by tibbi** [comment]
I dont see any hugely popular drawing app being opensource, that I could check which intents does it handle. One I found supported only Sharing into the app, nothing else. Guess the current way with image_capture is good enough, we will see on the feedback.

**Comment by daniele-athome** [comment]
To monitor intents from other apps (if you haven't tried it yet) you can use Intercept Intent (available on f-droid).

**Comment by gsantner** [comment]
are there any news or changes on this? @daniele-athome Could you please provide the invocation intent line of code? much appreciated :)

**Comment by daniele-athome** [comment]
@gsantner I've descrived the intent in my [original issue post](https://github.com/SimpleMobileTools/Simple-Draw/issues/47#issue-208834768), it's IMAGE_CAPTURE, just like when requesting a picture from the camera.
