### ISSUE TITLE
request: widget

### ISSUE THREAD

**Issue by RAWRR** [SimpleMobileTools/Simple-Draw#48]
The simplemobile calendar widget is great; swiping to get a screen that has a full calendar is so useful.

I'd love to get a similar widget for draw, where it has a full screen canvas. Just swipe and draw, basically. It would be even more excellent for taking notes, or quickly creating a diagram for help explaining something complex in conversations.

**Comment by tibbi** [comment]
widgets are really limited elements, you cannot draw on them. Swiping changes the homepage screen, and long pressing drags the widget. This cannot be implemented.
