### ISSUE TITLE
Add zoom functionality, endless canvas

### ISSUE THREAD

**Issue by tterranigma** [SimpleMobileTools/Simple-Draw#81]
I do not know if this fits with the aim of being simple. Here is [a description of what I have in mind](https://www.reddit.com/r/androidapps/comments/7udzz3/looking_for_a_simple_sketchdraw_app/).

Fingers crossed!

**Comment by tibbi** [comment]
maybe someday, but dont really expect it anytime soon.

**Comment by fghhfg** [comment]
:+1:

add `zoom in` & `zoom out` feature.

my fingers are too big :dizzy_face:

when I used this app in three minutes, I found out I needed this feature. :unamused:
