### ISSUE TITLE
Saving defaults to "Internal/Simple Draw", which doesn't exist: "An unknown error occurred"

### ISSUE THREAD

**Issue by 80tf3262p8** [SimpleMobileTools/Simple-Draw#83]
When you try to save a drawing for the first time, if you don't change the folder or create the default one manually, it fails with "An unknown error occurred."

Consider providing a more useful error or, better yet, create this folder if it doesn't exist.

Android 8.1 arm64, OnePlus 5, LineageOS 15.1 official 20180305 Nightly

**Comment by tibbi** [comment]
It should obviously crate the folder if it doesnt exist. So saving in a different folder or in "Simple Draw" after manual creation works fine?

**Comment by 80tf3262p8** [comment]
Yes.
