### ISSUE TITLE
Ability to change the save location is not obvious

### ISSUE THREAD

**Issue by 80tf3262p8** [SimpleMobileTools/Simple-Draw#84]
There is no browse icon, edit icon, or any other visual indicator that the save path can be changed by tapping or through any other method. When combined with another current issue (default save location doesn't exist, causing "unknown error"), the user finds themselves unable to save their drawing.

**Comment by tibbi** [comment]
ye it is the same behaviour at every dialog, I will add some indication someday.

**Comment by tibbi** [comment]
default save location has been fixed already. Ive made the save path easier to click, for now Im not sure what clickability indication should I put there. Anyway it is a more generic issue affecting more apps, so Ill close this issue.
