### ISSUE TITLE
Drawings made on portrait orientation are displaced in landscape orientation and vice versa

### ISSUE THREAD

**Issue by organik1** [SimpleMobileTools/Simple-Draw#90]
#### Expected behavior
Many people who love to draw have a habit of rotating their canvas inorder to draw easily. This should also be possible on the 'Draw app' without any glitch, hence drawing on landscape would fit into portrait during rotation and vise versa.

#### Actual behavior
Rotating the device when it is set to 'Auto rotate' changes the rotation of the screen, thereby  displacing the image  on the workspace. Sometimes a part is hidden, and someime the whole of it.

#### How to reproduce
* Set the device screen orientation to "Auto rotate"
* Launch the "Simple Draw App.
* make a drawing on its workspace
*Tilt the phone to 180° to use a different orientation
* And the bug should be visible.

# Testing Environment
* Browser: Google Chrome
* Operating system: Android version 7 (nougat)
* App Version: Draw v3.1.4

#### Recording Of The Bug
![20180313213126.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520974043/kwdv1saz5rqd9fjn6jpq.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@organik/drawings-made-on-portrait-orientation-are-displaced-in-landscape-orientation-and-vice-versa">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
of course it is in a different position at changing rotation..
