### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by eauchat** [SimpleMobileTools/Simple-Draw#93]
I think the UI could be simplified, with every tool being in the menu bar.
Also, the "C" button could be in the "more" menu, as it's in my opinion better if it's not to easy to access, to avoid deleting current drawing by accident.

Also it seems that the title "Draw" is not really necessary and could let space to have more tools in toolbar, or to make them distant and more easily clickable.
It could look like the following picture.

![simple-draw ui enhancement](https://user-images.githubusercontent.com/34686393/37614817-5ecc40fc-2bb4-11e8-9955-ad5042c937e6.png)

Maybe an even better option would be to have the drawing full screen and all tools in a sidemenu.

What do you think?

**Comment by tibbi** [comment]
The top menu is a system menu, I cannot customize is this way. I will do some UI changes someday, not sure yet how will it look like yet. Thanks though

**Comment by ppp0099** [comment]
Current UI also makes parts of the canvas impossible to draw on. I would support moving them to various bars.

**Comment by ppp0099** [comment]
Another solution to the above, very simple to implement: a button for a predefined alternative position of the on-canvas interface. For instance, it could move the buttons to the lower left corner, and move the size picker to the top.
