### ISSUE TITLE
Bug in Simple Draw: drawing clears after accessing settings

### ISSUE THREAD

**Issue by djavalord** [SimpleMobileTools/Simple-Draw#94]
#### Expected behavior
while drawing , click on setting, activate 'show brush size tool' from the setting,  then return to my drawing and continue  were i stopped

#### Actual behavior
while drawing , clicked on setting, activate 'show brush size tool', then return to my drawing  and all my work cleared.

#### How to reproduce
download simple draw version 3.1.5 from F-Droid on this address https://f-droid.org/packages/com.simplemobiletools.draw/ . install and run, draw anything on the draw board, click on the 3 dotted line at the top right hand side of the app, then select setting from the drop down menu,   activate 'show brush size tool' by clicking on it, then return to your work/drawing by clicking the return key at the top left hand side. the bug will be reproduced .

* Browser: Simple Draw version 3.1.5 
* Operating system: Android 5.1.1 Lollipop. Infinix hot 3 LTE

#### Recording Of The Bug
https://youtu.be/dFA9iDlRAM0
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@javalord/bug-in-simple-draw-drawing-clears-after-accessing-settings">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
dont you have some memory cleaner or so enabled? Or "Dont keep activities" in developer settings?
