### ISSUE TITLE
Unable to recover saved drawn object

### ISSUE THREAD

**Issue by fabianmani** [SimpleMobileTools/Simple-Draw#99]
#### Expected behavior
I expected after drawing and saving even after erasing the drawing pad to draw another image, I'd be able to open the saved drawing and either edit or continue drawing.

#### Actual behavior
The Saved drawing is opened into the drawing pad with stains of traces from the eraser tool, with the background colour as trace colour. Totally hiding what was drawn and saved. 

#### How to reproduce
* Download the app.
* change the default white background to any colour of your choice. 
* draw and save the image in png. 
* delete the drawn object then try opening the saved file. 

* Device: Tecno K7
* Operating system: Android 7.0
* App Version: 3.1.6

#### Recording Of The Bug
https://youtu.be/6siyq2umpD0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/unable-to-recover-saved-drawn-object">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
that is an ancient app version, open a new issue if it still happens
